version: '3.5'

services: 
  crud-cliente-backend:
    build: crud-cliente-backend
    ports:
      - "8080:8080"
    networks:
      - crud-cliente

  crud-cliente-frontend:
    build: crud-cliente-frontend
    depends_on:
        - crud-cliente-backend
    ports:
        - 3000:80
    networks:
      - crud-cliente
    links:
      - crud-cliente-backend:crud-cliente-backend   

networks:
  crud-cliente:
    driver: bridge 